// Monday email to Ria + Elliot: what changed this week, who hasn't replied in 21 days (call them — use the
// call-script-60s in templates/outreach), and new low-confidence rows. No creds → writes refresh/state/digest-<date>.md.
//   npx tsx refresh/weekly-digest.ts
import fs from 'node:fs';
import path from 'node:path';
import { Store, STATE_DIR, dateStr, addDays, daysSince, readChanges } from './lib/store';
import { gmailConfigured, sendEmail } from './lib/gmail';

(async () => {
  const store = await Store.open();
  const to = process.env.DIGEST_TO ?? 'riaarora016@gmail.com';
  const weekAgo = addDays(new Date(), -7).toISOString();
  const changes = readChanges(weekAgo);
  const byRow = new Map<string, any[]>(); for (const c of changes) byRow.set(c.name, [...(byRow.get(c.name) ?? []), c]);
  const noReply = store.inventory().filter((r) => r.last_emailed && daysSince(r.last_emailed) >= 21 && (!r.last_verified || r.last_verified < r.last_emailed));
  const lowConf = store.inventory().filter((r) => r.confidence === 'low' && r.last_verified && daysSince(r.last_verified) <= 7);
  const unverified = store.inventory().filter((r) => !r.last_verified || daysSince(r.last_verified) > 45);
  const fmt = (v: unknown) => (v == null || v === '' ? '—' : String(v));
  const lines = [
    `Biopunk housing — weekly digest (${dateStr()})`, '',
    `WHAT CHANGED (last 7 days): ${changes.length} field changes across ${byRow.size} rows`,
    ...[...byRow.entries()].slice(0, 40).map(([name, cs]) => `  • ${name}: ` + cs.flatMap((c: any) => Object.entries(c.changes).map(([k, v]: any) => `${k} ${fmt(v.from)} → ${fmt(v.to)}`)).slice(0, 4).join('; ')),
    '', `NO REPLY IN 21+ DAYS — please CALL these (templates/outreach/call-script-60s.md): ${noReply.length}`,
    ...noReply.map((r) => `  • ${r.name} — ${r.contact_phone || 'no phone on file'} — emailed ${r.last_emailed?.slice(0, 10)}`),
    '', `NEW LOW-CONFIDENCE ROWS (verified this week but only from a listing / no-reply): ${lowConf.length}`,
    ...lowConf.map((r) => `  • ${r.name}: ${r.notes.split(' | ').pop()}`),
    '', `UNVERIFIED (>45 days, hidden from the founder view): ${unverified.length} of ${store.inventory().length} inventory rows`,
    '', 'Pipeline tab (whole-building deals) is human-only — nothing automated touches it except listing-liveness checks.',
    'Generated by refresh/weekly-digest.ts · the founder view hides anything older than 45 days · reply to this email with corrections and a human will apply them.',
  ];
  const text = lines.join('\n');
  if (gmailConfigured() && !process.argv.includes('--dry-run')) { await sendEmail({ to, subject: `Biopunk housing digest — ${dateStr()}`, text }); console.log(`digest sent to ${to}`); }
  else { fs.mkdirSync(STATE_DIR, { recursive: true }); const f = path.join(STATE_DIR, `digest-${dateStr()}.md`); fs.writeFileSync(f, text + '\n'); console.log(`Gmail not configured → wrote ${f}\n\n${text}`); }
})();
